### ISSUE TITLE
Keep spaces in  a sentence. 

### ISSUE THREAD

**Issue by imranbarbhuiya** [words/metaphone#11]
This package removes all the spaces from any sentence.  

In [natural](http://naturalnode.github.io/natural/phonetics.html), They don't remove the spaces from the sentence.  But natural is a very big package that's why I want to use this package but I want to keep the spaces in place.

**Comment by wooorm** [comment]
Hi. metaphone is an algorithm for words, not for phrases, sentences, paragraphs, or say a whole book.
You can split the text you want to pass through it on your definition of “word”, pass each through this package, and join them back again. That way you control spaces, punctuation, symbols, etc. I don’t think one specific way of doing that would suit everyone’s needs, and hence it doesn’t make sense here

**Comment by imranbarbhuiya** [comment]
Thank you for your response. I'll do it by splitting the sentance.
